name       : qt5-svg
version    : 5.12.1
release    : 12
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.1/submodules/qtsvg-everywhere-src-5.12.1.tar.xz : 5bc1f744d32c06f5aa4eff33759568106a995ce21fa1326a247dfa5f783f63c8
license    :
    - GFDL-1.3
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 SVG Module
description: |
    Scalable Vector Graphics (SVG) is an XML-based language for describing two-dimensional vector graphics. Qt provides classes for rendering and displaying SVG drawings in widgets and on other paint devices.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtsvg.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
